- hosts: role_test
  # remote_user: root
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: Install cowsay
      become: true
      apt:
        name: cowsay
        state: present
    - shell: cowsay "coucou"
    - name: raw result of running date command"
      debug: msg="{{ lookup('pipe','date') }}"
